// Packs the repo's .KCC/ tree into src/generated/payload.ts so the compiled
// binary carries the framework and needs nothing else on the machine.
import { readdirSync, readFileSync, mkdirSync, writeFileSync, statSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { gzipSync } from "node:zlib";

const cliDir = join(import.meta.dir, "..");
const kccDir = join(cliDir, "..", ".KCC");
const pkg = JSON.parse(readFileSync(join(cliDir, "package.json"), "utf8")) as { version: string };

// Never shipped: per-project state and maintainer-only notes.
const EXCLUDE = [
  /^kcc\.lock$/,
  /^context\.md$/,
  /^tailoring\.exclude$/,
  /^\.tailored-out\//,
  /^TheChat\.md$/,
  /^kernel\/inspector\/proposals\/.+\.md$/,
];

function walk(dir: string, out: string[]): void {
  for (const name of readdirSync(dir).sort()) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) walk(full, out);
    else out.push(full);
  }
}

const all: string[] = [];
walk(kccDir, all);

const files: Record<string, { t?: string; b?: string }> = {};
for (const full of all) {
  const rel = relative(kccDir, full).split(sep).join("/");
  if (EXCLUDE.some((re) => re.test(rel))) continue;
  const buf = readFileSync(full);
  const text = buf.toString("utf8");
  if (Buffer.from(text, "utf8").equals(buf)) files[rel] = { t: text.replace(/\r\n/g, "\n") };
  else files[rel] = { b: buf.toString("base64") };
}

const json = JSON.stringify({ version: pkg.version, files });
const b64 = gzipSync(Buffer.from(json, "utf8"), { level: 9 }).toString("base64");

const outDir = join(cliDir, "src", "generated");
mkdirSync(outDir, { recursive: true });
writeFileSync(
  join(outDir, "payload.ts"),
  `// Generated by scripts/pack.ts. Do not edit.\nexport const PAYLOAD_VERSION = ${JSON.stringify(pkg.version)};\nexport const PAYLOAD_GZ_B64 = ${JSON.stringify(b64)};\n`,
);
console.log(`packed ${Object.keys(files).length} files (${(b64.length / 1024).toFixed(0)} KB) -> src/generated/payload.ts`);
