// Writes the package-manager files for a release from dist/checksums.txt:
//   dist/packaging/winget/Tikasway.KCC.*.yaml   (winget manifest, portable exe)
//   dist/packaging/homebrew/kcc.rb              (Homebrew formula for a tap)
// Usage: bun run scripts/packaging.ts   (after `bun run build:all` and the checksum step)
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const cliDir = join(import.meta.dir, "..");
const dist = join(cliDir, "dist");
const version = (JSON.parse(readFileSync(join(cliDir, "package.json"), "utf8")) as { version: string }).version;

const REPO = "TarekFawaz/kcc-agentic-framework";
const WINGET_ID = "Tikasway.KCC";
const HOMEPAGE = "https://tikasway.dev/kcc";
const DESCRIPTION = "Spec-driven, harness-neutral workflow framework for AI coding agents";
const base = `https://github.com/${REPO}/releases/download/v${version}`;

const sumsPath = join(dist, "checksums.txt");
if (!existsSync(sumsPath)) {
  console.error("dist/checksums.txt not found. Build every target and write the checksums first.");
  process.exit(1);
}
const sums = new Map<string, string>();
for (const line of readFileSync(sumsPath, "utf8").split(/\r?\n/)) {
  const m = /^([0-9a-fA-F]{64})\s+\*?(\S+)$/.exec(line.trim());
  if (m) sums.set(m[2] as string, (m[1] as string).toLowerCase());
}
function sha(asset: string): string {
  const s = sums.get(asset);
  if (!s) {
    console.error(`checksums.txt has no entry for ${asset}`);
    process.exit(1);
  }
  return s;
}

function write(rel: string, text: string): void {
  const path = join(dist, "packaging", rel);
  mkdirSync(join(path, ".."), { recursive: true });
  writeFileSync(path, text);
  console.log(`wrote dist/packaging/${rel}`);
}

// ---- winget: three-file manifest, portable installer (the bare exe, exposed as `kcc`) ----
const schema = "1.6.0";
write(
  `winget/${WINGET_ID}.yaml`,
  `# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.${schema}.schema.json
PackageIdentifier: ${WINGET_ID}
PackageVersion: ${version}
DefaultLocale: en-US
ManifestType: version
ManifestVersion: ${schema}
`,
);
write(
  `winget/${WINGET_ID}.installer.yaml`,
  `# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.${schema}.schema.json
PackageIdentifier: ${WINGET_ID}
PackageVersion: ${version}
InstallerType: portable
Commands:
- kcc
Installers:
- Architecture: x64
  InstallerUrl: ${base}/kcc-windows-x64.exe
  InstallerSha256: ${sha("kcc-windows-x64.exe").toUpperCase()}
ManifestType: installer
ManifestVersion: ${schema}
`,
);
write(
  `winget/${WINGET_ID}.locale.en-US.yaml`,
  `# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.${schema}.schema.json
PackageIdentifier: ${WINGET_ID}
PackageVersion: ${version}
PackageLocale: en-US
Publisher: Tikasway
PublisherUrl: https://tikasway.dev
PublisherSupportUrl: https://github.com/${REPO}/issues
Author: Tarek Fawaz
PackageName: KCC
PackageUrl: ${HOMEPAGE}
License: KCC License
LicenseUrl: https://github.com/${REPO}/blob/main/LICENSE
Copyright: KCC framework (c) 2026 Tarek Fawaz
ShortDescription: ${DESCRIPTION}
Description: The kcc command line installs, tailors, upgrades, and runs the KCC spec-driven workflow framework for Claude Code, Codex CLI, OpenCode, and other agent harnesses.
Moniker: kcc
Tags:
- ai
- agents
- cli
- developer-tools
- spec-driven
ReleaseNotesUrl: https://github.com/${REPO}/releases/tag/v${version}
ManifestType: defaultLocale
ManifestVersion: ${schema}
`,
);

// ---- Homebrew: formula for the tap repository (Formula/kcc.rb) ----
write(
  "homebrew/kcc.rb",
  `# Generated by cli/scripts/packaging.ts for release v${version}. Do not edit by hand.
class Kcc < Formula
  desc "${DESCRIPTION}"
  homepage "${HOMEPAGE}"
  version "${version}"
  license :cannot_represent

  on_macos do
    on_arm do
      url "${base}/kcc-darwin-arm64"
      sha256 "${sha("kcc-darwin-arm64")}"
    end
    on_intel do
      url "${base}/kcc-darwin-x64"
      sha256 "${sha("kcc-darwin-x64")}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/kcc-linux-arm64"
      sha256 "${sha("kcc-linux-arm64")}"
    end
    on_intel do
      url "${base}/kcc-linux-x64"
      sha256 "${sha("kcc-linux-x64")}"
    end
  end

  def install
    bin.install Dir["kcc-*"].first => "kcc"
    # The binaries are cross-compiled and unsigned; Apple Silicon refuses to run unsigned code.
    system "codesign", "--force", "--sign", "-", bin/"kcc" if OS.mac?
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kcc version")
  end
end
`,
);
